spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_avaliacao
spring.datasource.username=root
spring.datasource.password=Focus424487
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
