$kind: http-request
name: TRAINIG_PUT_ONE
url: http://localhost:8080/trainings/93d7c4ca-b94d-4289-85d3-f85a7cab980c
method: PUT
body:
  type: json
  content: "{\r

    \    \"title\": \"SOMETITLE\",\r

    \    \"initDate\": \"2026-05-20\",\r

    \    \"endDate\": \"2026-06-30\",\r

    \    \"workload\": 112,\r

    \    \"description\": \"Treinamento de SrpingBoot em Java.\"\r

    \r

    }"
order: 4454164672000229
