import type { Training } from "./types/Training";
import type { User } from "./types/User";


export const userMock: User = {
  nome: "Ana",
  sobrenome: "Santos",
  email: "ana.santos@ufal.br",
  telefone: "(82) 99999-9999",
  cargo: "gerenciador",
  permissoes: [
    { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
    { name: "gerenciarUsuarios", label: "Gerenciar Usuários", isEnabled: true },
    {
      isEnabled: true,
      label: "Gerenciar Treinamento",
      name: "gerenciarTreinamentos",
    },
    { name: "criarTreinamentos", label: "Criar Treinamentos", isEnabled: true },
  ],
};

export const trainingsMock: Training[] = [
  {
    id: 1,
    title: "LGPD e Proteção de Dados",
    hours: 72,
    progress: 10,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 5,
    status: "em_andamento",
  },
  {
    id: 2,
    title: "Lorem ipsum dolor",
    hours: 72,
    progress: 85,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 2,
    status: "avaliacao",
  },
  {
    id: 3,
    title: "Lorem ipsum dolor",
    hours: 72,
    progress: 15,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 0,
    status: "pre_avaliacao",
  },
  {
    id: 4,
    title: "Lorem ipsum dolor",
    hours: 72,
    progress: 0,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 15,
    status: "aguardando_feedback",
  },
  {
    id: 5,
    title: "Lorem ipsum dolor",
    hours: 72,
    progress: 100,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 0,
    status: "concluido",
  },
  {
    id: 6,
    title: "Lorem ipsum dolor",
    hours: 72,
    progress: 85,
    startDate: "20/05",
    endDate: "30/06",
    daysLeft: 0,
    status: "pendencia",
  },
];
export const colaboradores = [
  {
    id: 1,
    nome: "João",
    sobrenome: "Silva",
    cpf: "123.456.789-00",
    email: "joao.silva@email.com",
    cargo: "colaborador",
    telefone: "(11) 1234-5678",
    situacao: "Ativo",
    permissoes: [
      { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
      {
        name: "gerenciarUsuarios",
        label: "Gerenciar Usuários",
        isEnabled: false,
      },
      {
        name: "gerenciarTreinamentos",
        label: "Gerenciar Treinamento",
        isEnabled: false,
      },
      {
        name: "criarTreinamentos",
        label: "Criar Treinamentos",
        isEnabled: false,
      },
    ],
    treinamentosIds: [1, 2],
  },
  {
    id: 2,
    nome: "Maria",
    sobrenome: "Souza",
    cpf: "234.567.890-11",
    email: "maria.souza@email.com",
    cargo: "colaborador",
    telefone: "(11) 1234-5678",
    situacao: "Inativo",
    permissoes: [
      { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
      {
        name: "gerenciarUsuarios",
        label: "Gerenciar Usuários",
        isEnabled: false,
      },
      {
        name: "gerenciarTreinamentos",
        label: "Gerenciar Treinamento",
        isEnabled: false,
      },
      {
        name: "criarTreinamentos",
        label: "Criar Treinamentos",
        isEnabled: false,
      },
    ],
    treinamentosIds: [2, 3],
  },
  {
    id: 3,
    nome: "Carlos",
    sobrenome: "Oliveira",
    cpf: "345.678.901-22",
    email: "carlos.oliveira@email.com",
    cargo: "gerenciador",
    telefone: "(11) 1234-5678",
    situacao: "Ativo",
    permissoes: [
      { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
      {
        name: "gerenciarUsuarios",
        label: "Gerenciar Usuários",
        isEnabled: true,
      },
      {
        name: "gerenciarTreinamentos",
        label: "Gerenciar Treinamento",
        isEnabled: true,
      },
      {
        name: "criarTreinamentos",
        label: "Criar Treinamentos",
        isEnabled: true,
      },
    ],
    treinamentosIds: [1, 3, 4],
  },
  {
    id: 4,
    nome: "Ana",
    sobrenome: "Pereira",
    cpf: "456.789.012-33",
    email: "ana.pereira@email.com",
    cargo: "colaborador",
    telefone: "(11) 1234-5678",
    situacao: "Ativo",
    permissoes: [
      { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
      {
        name: "gerenciarUsuarios",
        label: "Gerenciar Usuários",
        isEnabled: false,
      },
      {
        name: "gerenciarTreinamentos",
        label: "Gerenciar Treinamento",
        isEnabled: false,
      },
      {
        name: "criarTreinamentos",
        label: "Criar Treinamentos",
        isEnabled: false,
      },
    ],
    treinamentosIds: [4],
  },
  {
    id: 5,
    nome: "Lucas",
    sobrenome: "Fernandes",
    cpf: "567.890.123-44",
    email: "lucas.fernandes@email.com",
    cargo: "colaborador",
    telefone: "(11) 1234-5678",
    situacao: "Inativo",
    permissoes: [
      { name: "verTreinamentos", label: "Ver Treinamentos", isEnabled: true },
      {
        name: "gerenciarUsuarios",
        label: "Gerenciar Usuários",
        isEnabled: false,
      },
      {
        name: "gerenciarTreinamentos",
        label: "Gerenciar Treinamento",
        isEnabled: false,
      },
      {
        name: "criarTreinamentos",
        label: "Criar Treinamentos",
        isEnabled: false,
      },
    ],
    treinamentosIds: [],
  },
] 
